### ISSUE TITLE
When reloading plugin the sources classes are None

### ISSUE THREAD

**Issue by ruz76** [OpenGeoLabs/czech_slovak_freegeodata#2]
If you start QGIS everyting is fine, but when developing and you reload the plugin then the array self.data_sources is empty ot the objects inside it are None.

**Comment by PetoP** [comment]
I am unable to reproduce this issue. I added print(self.data_sources) right after calling self.load_sources_into_tree() in GeoDataDialog().__init__(). After reloading plugin (via Plugin Reloader plugin), I am always getting full array with valid data sources (same output as when after fresh QGIS start).

Any idea what should I bee doing differently to reproduce this bug?
