### ISSUE TITLE
Region choice window opened in background on Windows

### ISSUE THREAD

**Issue by PetoP** [OpenGeoLabs/czech_slovak_freegeodata#35]
I have received message from a fried about presumably bad behavior of region choice window. He has tested this on three independent machines running Windows 10 Pro, always on QGIS 3.18 with new clean profile. After first opening of the main plugin window it takes long time (as reported) before window for region choice is opened and when it does, it opens behind main QGIS window. Thus user not knowing about this window may get really frustrated.

**Comment by lieti** [comment]
I can confirm this bug (another WIN10, QGIS 3.18)
Long time to recieve reaction on button from toolbar, than window is opened behind main QGIS window, users are confused.

**Comment by ruz76** [comment]
The window has been removed, but the bug still remains. The whole main window is behind QGIS Window.
