### ISSUE TITLE
Pridať ďalšie WMS

### ISSUE THREAD

**Issue by Slavomir9** [OpenGeoLabs/czech_slovak_freegeodata#47]
Dobrý deň,
priznám sa, že sa v GitHub veľmi nerozumiem. Rád by som požiadal o pridanie WMS mám a neviem, kde mám hľadať kontakt.
Mohli by ste prosím pridať uvedené mapy? Nie všetky fungujú, ale aspoň tie ktoré fungujú
Ďakujem

Geologická mapa
https://ags.geology.sk/arcgis/services/WebServices/GM50/MapServer/WMSServer

Lesnícke mapy
https://gis.nlcsk.org/islhp/
https://gis.nlcsk.org/arcgis/rest/services/Inspire

    • Inspire/DrevinoveZlozenie https://gis.nlcsk.org/arcgis/services/Inspire/DrevinoveZlozenie/MapServer/WMSServer?request=GetCapabilities&service=WMS
    • Inspire/JPRL https://gis.nlcsk.org/arcgis/services/Inspire/JPRL/MapServer/WMSServer?request=GetCapabilities&service=WMS
    • Inspire/LesneCesty https://gis.nlcsk.org/arcgis/services/Inspire/LesneCesty/MapServer/WMSServer?request=GetCapabilities&service=WMS
    • Inspire/LesneOblasti https://gis.nlcsk.org/arcgis/services/Inspire/LesneOblasti/MapServer/WMSServer?request=GetCapabilities&service=WMS
    • Inspire/LesneTypy https://gis.nlcsk.org/arcgis/services/Inspire/LesneTypy/MapServer/WMSServer?request=GetCapabilities&service=WMS
    • Inspire/LHC https://gis.nlcsk.org/arcgis/services/Inspire/LHC/MapServer/WMSServer?request=GetCapabilities&service=WMS
    • Inspire/PodneTypy https://gis.nlcsk.org/arcgis/services/Inspire/PodneTypy/MapServer/WMSServer?request=GetCapabilities&service=WMS
    • Inspire/PolovneReviry https://gis.nlcsk.org/arcgis/services/Inspire/PolovneReviry/MapServer/WMSServer?request=GetCapabilities&service=WMS
    • Inspire/TMP https://gis.nlcsk.org/arcgis/services/Inspire/TMP/MapServer/WMSServer?request=GetCapabilities&service=WMS
    • Inspire/TokySR https://gis.nlcsk.org/arcgis/services/Inspire/TokySR/MapServer/WMSServer?request=GetCapabilities&service=WMS
    • Inspire/TVP https://gis.nlcsk.org/arcgis/services/Inspire/TVP/MapServer/WMSServer?request=GetCapabilities&service=WMS

**Comment by ruz76** [comment]
Děkuji. Bezva. Zařadíme do další verze pluginu.

**Comment by Slavomir9** [comment]
Dobrý deň,
ďakujem Vám veľmi pekne za ochotu.
Pokiaľ pridáte nové mapy do doplnku, tak určite ich bude využívať desiatky až stovky ľudí. Mám významný dosah v lesníckych FB skupinách, takže môžem to spropagovať.
Mimochodom aj geologické mapy významne využívajú lesníci a je veľmi dobré ich skombinovať v jednotnej platforme.
Lesnícke mapy vytvorilo NLC (Národné lesnícke centrum).

Neviem či budete potrebovať tieto odkazy, nie sú to priamo WMS mapy, ale dám ich tu:
https://www.mojevideo.sk/video/39449/nove_polovnicke_mapy_mapa_revirov.html
https://www.mojevideo.sk/video/391e6/nove_lesnicke_mapy_navod_na_pouzivanie.html

**Comment by PetoP** [comment]
Ahojte,

pridal som väčšinu z požadovaných WMS služieb:
- GM50
- Drevinové zloženie
- Lesné cesty
- Lesné typy
- TMP
- Toky
- TVP

Zvyšné robia robia pri WMS problémy:
- JPRL, LHC a Polovné revíry pri pokuse o stiahnutie capabilít vrátia: The download of the specified resource has failed.
- Lesné oblasti a pôdne typy zasa vyhadzujú chybu: Parameter 'layers' contains unacceptable layer names. Ako parameter layers som pritom skúsil použiť v capabilitách deklarovaný Title, 0 alebo show:0 (ten som okukal že používa ARCGIS REST zobrazovacia služba). Rovnako končí aj QGIS, keď link na dané WMS použijem na štandardné pridanie WMS služby cez Data Source Managera.

Vrstvy ktoré neviem rozbehať cez WMS evidentne fungujú cez ARCGIS REST API. [Horeuvedený webový prehliadač](https://gis.nlcsk.org/islhp/) používa práve túto technológiu na ich zobrazenie. Túto technológiu síce QGIS pozná, no nemám s ňou skúsenosti (a rád sa jej budem vyhýbať pokiaľ to len bude možné) a ani plugin ju nemá implementovanú, takže jej použitie by bol dlhým behom bez istého výsledku.

@Slavomir9, prosím, ak náhodou máte dosah na ľudí z NLC, skúste ich poprosiť o vyriešenie uvedených problémov s WMS. V prípade že by od nás potrebovali pomoc/spätnú väzbu. kontaktovať nás už viete :) 

@ruz76, skontroluj to prosím po mne. Pribudli dve nové skupiny vrstiev - NLC a SGÚDŠ.

Dík,
Peťo

**Comment by ruz76** [comment]
Děkuji moc. Vše funguje. Teda ty výzkumné a monitorovací plochy jako body je trochu podivnost, ale to už není náš problém.

Počkáme na ty problematické WMS nebo uděláme release s těmito 7 novými vrstvami? Asi bych udělal release, dlouho jsme neudělali update. Jen bych možná zkusil dopsat nějaký ten lehký monitoring, ať případně vyřadíme služby, které padají na čumák.

**Comment by PetoP** [comment]
Super! Ja si myslím že urobme teraz. Ak by sa s tým aj niečo pohlo, tak spravíme znova.

Monitoring - áno, o tom sme sa predsa už bavili dávnejšie. Rozhodne som za, akurát ja si to v blízkej budúcnosti na seba isto neviem zobrať.

**Comment by ruz76** [comment]
Jasně. Já bych do klienta teď asi jen dopsal, že si bude číst od někud (asi github) nějaký status služby a zobrazovat semafor u služeb podle stavu. Zatím by tam byla všude zelená a pak bych dopsal službu, která by to každý den projela a výsledky zapsala na github.

**Comment by Slavomir9** [comment]
Ďakujem Vám obom veľmi pekne za ochotu.
Peťo: Áno, mám kontakty v NLC, píšeme si emaily. Práve včera mi zamestnanec odpísal, že pracuje na WMS mapách. Aj som včera testoval mapy a zdá sa, že časť chýb opravil. Ale prepošlem mu tieto návrhy na opravy.
Zaujímavé, že ešte včera večer mi fungovali revíry a teraz to znovu nefunguje, možno tam robil nejaké testy.

Tiež mi písal, že možno budú aj meniť súradnicový systém na WGS84 Web Mercator (kód EPSG:3857), tak aby boli WMS mapy kompatibilné so ZBGIS.sk aplikáciou, pretože aj do nej sa dajú mapy importovať WMS vrstva.
(Alebo možno plánujú skôr pridať ako meniť súradnicový systém, lebo pokiaľ sa nemýlim, tak WMS mapy dokážu pracovať aj s viacero vybranými súradnicovými systémami).

Spomínal, že pracujú na pridaní porastovej WMS mapy.

V prílohe aj pridávam zoznamy WMS adries, ktoré mi poslal.

A len ako taká poznámka na okraj, napríklad cesty a toky mi dokáže v Aplikácii Locus map pekne zobraziť na popredí bez toho aby mapa na popredí napr cesty prekrývala základnú mapu na posadí. V QGIS mi mapa popredia prekryje základnú mapu pozadia úplne.
Existuje nejaké jednoduché riešenie na tento problém?
(Hľadal som nejaké nastavenia vo vrstvách, ale nenašiel som)

Ale zaujímavé že JPRL mi teraz vedelo v QGIS zobraziť správne, bez úplného prekrytia základnej mapy pozadia. 


[WMS_WFS_sluzby.docx](https://github.com/OpenGeoLabs/czech_slovak_freegeodata/files/10697596/WMS_WFS_sluzby.docx)

**Comment by Slavomir9** [comment]
Tak to je v pohode. Mapy ISLHP nemusíš pridávať, nakoľko ako hovoríš, je to na veľa roboty.
Tu posielam aj video, problém s tým prekrývaním
https://www.youtube.com/watch?v=f1DNIpivMmA

**Comment by PetoP** [comment]
Ahoj @Slavomir9,

súradnicový systém - áno, WMS server vie definovať množinu súradnicových systémov v ktorých je možné vypýtať si mapový obrázok. Ak sa pod "prechodom na EPSG:3857" rozumie to, že ho pridajú, tak to na nás nemá žiaden vplyv (my používame 5514, ktorý tam v zozname stále našťastie je).

Priesvitnosť - áno, všimol som si a WMS v plugine som rovno nastavil tak, aby bola priesvitná. Keď si ju pridávaš normálne cez Data Source Managera, musíš po stlačení tlačítka Connect pod zoznamom vrstiev vybrať formát PNG. Defaultne je tam totiž JPEG (neviem prečo, možno preto že je ako prvý v kapabilitách, hneď za BMP ktoré asi nie je podporované QGISom) a ten nepodporuje priehľadnosť. Locus možno automaticky skočí po PNG (to neviem, len si domýšľam).

Prešiel som zaslaný zoznam WMS služieb. Ku NLC vrstvám som pridal všetky uvedené s jedinou výnimkou - Lesné oblasti stále hádžu Parameter 'layers' contains unacceptable layer names pri použitý LAYERS=LC.LandCoverSurfaces.

Pridal som aj všetky v zozname uvedené vrstvy MPRV SR, takže okrem doplnenia skupiny NLC vznikla aj nová skupina MPRV SR. @ruz76, prosím, pre istotu to po mne zasa prejdi. Neviem či rovno robiť nový release alebo, keďže to tu máme trochu dynamické, počkať ešte pár dní na to, či sa ešte niečo zmení. Nechal by som to na Tvoje rozhodnutie a možnosti.

Ešte ohľade spomínaného semafóru - áno, znie to ako najpriamočiarejšie a funkčne plnohodnotné riešenie, som plne za.

Pekný víkend želám,
Peťo

**Comment by Slavomir9** [comment]
Peťo: Ďakujem za skvelú prácu.
Super rada s tým PNG JPG nastaveniami. Funguje mi :).
A preposlal som to chybové hlásenie zamestnancovi.

Tak verím, že aj menej PC zdatných lesníkov budú dari, že sa budú môcť pohrať s týmito mapami. Doplnok je super vec :).

**Comment by ruz76** [comment]
@PetoP Klidně můžeme chvíli počkat. Já zatím dodělám ten semafor. 
![image](https://user-images.githubusercontent.com/15860810/218287825-081c6a8e-260d-48bf-8188-b11824aee3e8.png)

Mám další dobrou zprávu. Díky té implementaci semaforu jsem našel tu chybu, která zpomaluje načtení zdrojů do okna. Taková běžná chyba a nikdo z nás to neviděl, tam se při každém načtení jednoho zdroje znova načítá celé okno, tedy teď už 149 (takže zrychlení 149x). Takže udělám fix i s tím semaforem a pak někdy příští víkend udělám release.

**Comment by ruz76** [comment]
@PetoP Jinak jsem ty nové NLC a MPRV prošel a vše funguje. Děkuji.

**Comment by Slavomir9** [comment]
@[ruz76](https://github.com/ruz76) tak to som veľmi rád, že sa ti to podarilo vylepšiť. Načítavalo to neprimerane dlho, to som postrehol :)

**Comment by Slavomir9** [comment]
![Firefox_Screenshot_2023-02-26T21-48-44 227Z](https://user-images.githubusercontent.com/73296504/221442699-be681de3-ef13-479e-9998-4156dd07ea84.png)
![Firefox_Screenshot_2023-02-26T21-43-09 549Z](https://user-images.githubusercontent.com/73296504/221442706-5aae49ba-04bd-4086-a4a3-ed1e9398fe53.png)
Dobrý deň,
ahojte.
Ešte by som mal na vás prosbu pridať aj Heatmap od US firmy Strava z Freemap.sk.
Jedná sa o monitoring športových aktivít, resp. koncentrácie pohybu ľudí všeobecne. Často zobrazí aj na mapách nevyznačené cesty.
Výhoda že freemap.sk nepodporuje len Slovensko ale aj Česko a ďalšie okolité štáty.
https://wiki.openstreetmap.org/wiki/Strava
Na freemap.sk vám to zobrazí pod položkou „Strava“.
Verím, že by to snáď nemalo byť veľa práce to pridať. 

Niečo ako adresa by údajne malo asi byť:
[https://strava-heatmap.tiles.freemap.sk/ride/hot/{z}/{x}/{y}.png](https://strava-heatmap.tiles.freemap.sk/ride/hot/%7Bz%7D/%7Bx%7D/%7By%7D.png)


_<div><sub>A len ako tak&aacute; pozn&aacute;mka na okraj: Ja by som e&scaron;te cez t&uacute;to možnosť chcel pridať aj lesn&eacute; cesty do OpenStreetMap (OSM). T&yacute;ch možnost&iacute; je asi viacero ako pridať, ale jedn&aacute; z nich by bola aj cez QGIS, keď by som si najprv vytvoril/vykreslil GPX s&uacute;bor v QGIS a potom ho importovať do OSM.</sub></div>
<div><sub>Pridať cesty na z&aacute;klade heatmap je lep&scaron;ie ako na z&aacute;klade GPX z&aacute;znamu z m&ocirc;jho telef&oacute;nu, pretože tam m&ocirc;že byť pr&iacute;li&scaron; veľk&aacute; nepresnosť. Heat map m&aacute; nepresnosti / hodnoty z&aacute;znamov spriemerovan&uacute;, takže je možn&eacute; podstatne presnej&scaron;ie určiť kde sa cesta nach&aacute;dza</sub></div>
<div><sub>Ale to som už odbočil od t&eacute;my sorry :).</sub></div>_

<p></p>
<p></p>
<p></p>
<p></p>
A z NLC mi odpísali, že ešte bude niečo trvať, kým sa dostanú ku WMS mapám. Sú zaneprázdnení.

**Comment by ruz76** [comment]
Ahoj. Díky. Tak tento další zdroj už do dalšího release. Udělám to jako nové issue. Release jsem vydal minulý týden, tak počkáme zase chvíli až se něco sejde. @kalab-oto říkal, že má tady nějaké nové zdroje. Tak třeba za 2-3 týdny bychom mohli udělat další release.

**Comment by Slavomir9** [comment]
Ďakujem za ochotu. Testoval som aktualizáciu a funguje to výborne.
