### ISSUE TITLE
ZBGIS data not working

### ISSUE THREAD

**Issue by mikislav** [OpenGeoLabs/czech_slovak_freegeodata#7]
sources vyskopis/vegetacia/vodstvo not working

**Comment by ruz76** [comment]
It works for me, but you have to zoom in. These layers have zoom level restrictions.

**Comment by ruz76** [comment]
![image](https://user-images.githubusercontent.com/15860810/108769004-b3db5600-7558-11eb-8c89-559ef4996b03.png)

**Comment by mikislav** [comment]
yes, you are right. thx

**Comment by mikislav** [comment]
data source working after deeper zoom in
