### ISSUE TITLE
WMS UHUL

### ISSUE THREAD

**Issue by ruz76** [OpenGeoLabs/czech_slovak_freegeodata#8]
Milí vývojáři,
super, díky za velice užitečný počin!
Jako námět pro rozšíření bych se přimlouval i za začlenění vrstev ÚHÚL: http://www.uhul.cz/mapy-a-data/webove-sluzby
Myslím, že principiálně by to neměl být žádný problém.
Ať se daří.
Ondřej Špulák

**Comment by kalab-oto** [comment]
Toto jsem měl v plánu, ale  bude z toho třeba vybrat, je tam hromada vrstev.  

Jde do `metadat.ini` přidat více vrstev? Pokud ne tak toto by mohla být další featura. Napadá mě, že by se mohlo místo jedné vrstvy do QGIS, přidat více vrstev do samostatné skupiny (group).

Toto je např. WMS OPRL
![obrazek](https://user-images.githubusercontent.com/13303725/108833129-ac559480-75cc-11eb-8d08-1be1a8223b17.png)

**Comment by ruz76** [comment]
Dá se přidat více vrstev, tak, že se chovají pak jako jedna vrstva, takže vlastně kompozice. Ale chová se to pak v QGISu jako jedna vrstva. Viz např. https://github.com/OpenGeoLabs/czech_slovak_freegeodata/blob/main/data_sources/ZBGIS_vyskopis_SR/metadata.ini
